### PR TITLE
Created a sticky nav style for the player

### PR DESCRIPTION
**Pull request by designMoreWeb**
## What's this PR do?
-  Added smooth scroll behaviour to the html
-  Added a media query that gets trigged as soon as you scroll past the player and remains on top of the page like a nav bar, this is so the user can scroll to the bottom of the page to read the transcription of the podcast while accessing the player and its controls
## Where should the reviewer start?
- Load any page with the podcast
- Start scrolling past the player
- see if the player works and sticks
## How should this be manually tested?
- Same as above
Any background context you want to provide?
- Saw an accessibility concern in the issues and thought of helping out
What are the relevant tickets?
Fixes issue #73  [https://github.com/ladybug-podcast/ladybugpodcast/issues/73]

### CODE REVIEW

**Comment by moudev** [comment]
Hi, I made another version if you want to check it. #80

**Comment by designMoreWeb** [comment]
> Hi, I made another version if you want to check it. #80

Hey I saw it while it looks good a lot of the code feels unnecessary when you can do it with a simple media query the JS option is good but doing it in css keeps it simpler in my view and gives more flexibility to the player. But still good job

**Comment by emmabostian** [comment]
Hey! We appreciate the PR! We actually decided to go with #80 because we like the bottom-sticky and aesthetics of it a bit more but we REALLY appreciate your contribution! :)

**Comment by designMoreWeb** [comment]
My pleasure always ready to help out :)

**Pull request closed without merging**
